config/routes.rb
Rails.application.routes.draw do

  root              to: 'static_pages#home',    as: :root
  get '/help'     , to: 'static_pages#help'
  get '/about'    , to: 'static_pages#about',   as: :about
  get '/contact'  , to: 'static_pages#contact'

  get '/signup'   , to: 'users#new'

  resources :users
  resources :microposts

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base

  belongs_to :user
  validates :content, :length => { :maximum => 101 }

end

app/models/user.rb
class User < ActiveRecord::Base

  # attr_accessor :email, :name
  has_many :microposts

  validates :name, :length => { :minimum => 2 }
  validates :email, :length => { :minimum => 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

    def index
      @microposts = Micropost.all
    end

    def show
      @micropost = Micropost.find(params[:id])
    end

    def new
      @micropost = Micropost.new
    end

    def create
      @micropost = Micropost.new(micropost_params)
      @micropost.save
      redirect_to @micropost
    end

    def edit
      @micropost = Micropost.find(params[:id])
    end

    def update
      @micropost = Micropost.find(params[:id])

      if @micropost.save
        redirect_to @micropost
      else
        render 'edit'
      end
    end

    def destroy
      @micropost = Micropost.find(params[:id])
      @micropost.destroy

      redirect_to microposts_path
    end

    private
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		render :json => {'name' => 'Ram', 'place' => 'Mumbai' }
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper


  def full_title(title)
    
    base_title = "Ruby on Rails Tutorial Sample App"
    if title.blank?
      return base_title
    else
      return "#{base_title} | #{title}"
    end

  end


end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer"> <small>
<a href="http://railstutorial.org/">Rails Tutorial</a>
    by Ravi
  </small>
  <nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
</ul> </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top pull-right">
  <div class="navbar-inner">
<div class="container">
<%= link_to "sample app", root_path, id: "logo" %> <nav>
<ul class="nav pull-right">
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Help", help_path %></li>
<li><%= link_to "Sign in", '#' %></li>
</ul> </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
  </head>

  <body>

    <%= render 'layouts/header' %> <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %> </div>

  </body>
</html>

  </head>
  <body>

  </body>
</html>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>
 
<%= form_for :micropost, url: micropost_path(@micropost), method: :patch do |f| %>
 
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@micropost.errors.count, "error") %> prohibited
        this micropost from being saved:
      </h2>
      <ul>
        <% @micropost.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>
 
  <p>
    <%= f.label :user_id %><br>
    <%= f.text_area :user_id %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>

<tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
</tr>

<% @microposts.each do |micropost| %>
<tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, confirm: 'Are you sure?', method: :delete %></td>
￼￼￼￼￼￼</tr>
<% end %>

</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<%= form_for :micropost, url: microposts_path do |f| %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>

  <p>
    <%= f.label :User %><br>
    <%= f.text_area :user_id %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'All posts', microposts_path %>

app/views/microposts/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'All microposts', microposts_path %>

app/views/static_pages/about.html.erb
<h1>About Us</h1>

<p>The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> is a project to make a book and screencasts to teach web development with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>
  Ruby on Rails Tutorial Sample App, 
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>

<p>Get help on the Ruby on Rails Tutorial at the
    <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
    To get help on this sample app, see the <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center navbar-default"> <h1>Welcome to the Sample App</h1>
<h2>
This is the home page for the
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
</h2>
<%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %> </div>
<%= link_to image_tag("rails.jpg", alt: "Rails", size: "60x80"), 'http://rubyonrails.org/' %>

app/views/users/edit.html.erb
<h1>Editing user</h1>
 
<%= form_for :user, url: user_path(@user), method: :patch do |f| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>

<tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
</tr>

<% @users.each do |user| %>
<tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
￼￼￼￼￼￼</tr>
<% end %>

</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<title> Signup </>
  
<p>Find me in app/views/users/new.html.erb</p>
￼￼￼￼￼￼￼

<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'All users', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'All users', users_path %>